version: '3'

services:
  mongodb:
    build:
      context: ./db
      dockerfile: Dockerfile

    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb